/**
 * Export utilities for CSV and PDF report generation.
 */
import type { PredictionResult } from '../types/prediction';

// ─── CSV Export ──────────────────────────────────────

function escapeCSV(val: string | number): string {
  const str = String(val);
  if (str.includes(',') || str.includes('"') || str.includes('\n')) {
    return `"${str.replace(/"/g, '""')}"`;
  }
  return str;
}

export function exportDailyCSV(result: PredictionResult): void {
  const headers = [
    'Date', 'Label', 'Predicted Count', 'Risk Level', 'Confidence %',
    'Traffic', 'Best Time', 'Worst Time', 'Weather', 'Temp °C', 'Events',
  ];

  const rows = result.dailyForecasts.map((d) => [
    d.date,
    d.label,
    d.predictedCount,
    d.riskLevel,
    d.confidence,
    d.trafficIntensity,
    d.bestTime,
    d.worstTime,
    d.weather?.condition || 'N/A',
    d.weather?.tempC ?? 'N/A',
    d.events.map((e) => e.name).join('; ') || 'None',
  ]);

  const csv = [
    headers.map(escapeCSV).join(','),
    ...rows.map((row) => row.map(escapeCSV).join(',')),
  ].join('\n');

  downloadFile(csv, `crowd_prediction_${result.location.id}_${result.dateRange.start}.csv`, 'text/csv');
}

export function exportHourlyCSV(result: PredictionResult): void {
  const headers = ['Hour', 'Predicted Count', 'Is Peak', 'Risk Level'];

  const rows = result.hourlyToday.map((h) => [
    h.hour, h.count, h.isPeak ? 'Yes' : 'No', h.riskLevel,
  ]);

  const csv = [
    headers.map(escapeCSV).join(','),
    ...rows.map((row) => row.map(escapeCSV).join(',')),
  ].join('\n');

  downloadFile(csv, `hourly_prediction_${result.location.id}_${result.dateRange.start}.csv`, 'text/csv');
}

// ─── PDF Export (text-based, no external library) ────

export function exportPDF(result: PredictionResult): void {
  // Build a clean text report and open in new window for printing
  const lines: string[] = [];

  lines.push('═══════════════════════════════════════════════════');
  lines.push('  PILGRIMENT — AI Crowd Prediction Report');
  lines.push('═══════════════════════════════════════════════════');
  lines.push('');
  lines.push(`Location:     ${result.location.name}, ${result.location.state}`);
  lines.push(`Generated:    ${new Date(result.generatedAt).toLocaleString()}`);
  lines.push(`Date Range:   ${result.dateRange.start} → ${result.dateRange.end}`);
  lines.push(`Confidence:   ${result.overallConfidence}%`);
  lines.push(`Data Sources: ${result.dataSourcesUsed.join(', ')}`);
  lines.push('');
  lines.push('── Summary ──────────────────────────────────────');
  lines.push(result.summary);
  lines.push('');
  lines.push('── Daily Forecast ───────────────────────────────');
  lines.push('Date        | Label     | Crowd    | Risk     | Traffic  | Best  | Worst');
  lines.push('─'.repeat(80));

  for (const d of result.dailyForecasts) {
    lines.push(
      `${d.date}  | ${d.label.padEnd(9)} | ${String(d.predictedCount).padStart(8)} | ${d.riskLevel.padEnd(8)} | ${d.trafficIntensity.padEnd(8)} | ${d.bestTime} | ${d.worstTime}`
    );
  }

  lines.push('');
  lines.push('── Today Hourly Breakdown ───────────────────────');
  lines.push('Hour   | Count  | Peak | Risk');
  lines.push('─'.repeat(40));

  for (const h of result.hourlyToday) {
    lines.push(
      `${h.hour}  | ${String(h.count).padStart(6)} | ${h.isPeak ? ' ★  ' : '    '} | ${h.riskLevel}`
    );
  }

  lines.push('');
  lines.push('── Weather Data ─────────────────────────────────');
  for (const d of result.dailyForecasts) {
    if (d.weather) {
      lines.push(`${d.date}: ${d.weather.condition}, ${d.weather.tempC}°C, Rain ${d.weather.rainChance}%, Wind ${d.weather.windKph} km/h`);
    }
  }

  lines.push('');
  lines.push('── Events / Holidays ───────────────────────────');
  for (const d of result.dailyForecasts) {
    if (d.events.length > 0) {
      lines.push(`${d.date}: ${d.events.map(e => `${e.name} (${e.type}, impact: ${(e.impactScore * 100).toFixed(0)}%)`).join(', ')}`);
    }
  }

  lines.push('');
  lines.push('═══════════════════════════════════════════════════');
  lines.push('  Generated by PILGRIMENT Smart Crowd Management');
  lines.push('═══════════════════════════════════════════════════');

  const report = lines.join('\n');

  // Open print dialog
  const printWindow = window.open('', '_blank');
  if (printWindow) {
    printWindow.document.write(`
      <html>
        <head>
          <title>PILGRIMENT Prediction Report — ${result.location.name}</title>
          <style>
            body { font-family: 'Courier New', monospace; font-size: 12px; padding: 40px; background: #fff; color: #000; line-height: 1.5; }
            @media print { body { padding: 20px; } }
          </style>
        </head>
        <body><pre>${report}</pre></body>
      </html>
    `);
    printWindow.document.close();
    printWindow.print();
  }
}

// ─── Helper ──────────────────────────────────────────

function downloadFile(content: string, filename: string, type: string): void {
  const blob = new Blob([content], { type: `${type};charset=utf-8;` });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  link.style.display = 'none';
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
